#!/usr/bin/env zsh
    if (($#<2)) {
        {
        print -- 'usage: fold function list'
        print 
        print -- 'example:'
        print -- '    > bar() { print $(($1 + $2)) }' 
        print -- '    > fold bar 0 1 2 3 4 5' 
        print -- '    15'
        } >&2
        return 1
    }
    if (($#<3)) {
        print -- $2
        return 0
    } else {
        local acc
        local right
        local func_name=$1
        local init_value=$2
        local first_value=$3
        shift 3
        right=$( fold $func_name $init_value $@ )
        acc=$( eval "$func_name $first_value $right" )
        print -- $acc
        return 0
    }
