#!/usr/bin/env zsh

map() {
    (($#<1)) && {
            print -- "usage: map funcname [list]"
            print 
            print -- 'example:'
            print -- '    > foo(){print "x: $1"}'
            print -- '    > map foo a b c d'
            print -- '    x: a'
            print -- '    x: b'
            print -- '    x: c'
            print -- '    x: d'
            return 1
        }
    local func_name=$1
    shift
    for elem in $@; print -- $(eval $func_name $elem)
}
